### PR TITLE
Router ssl - round 2

### PR DESCRIPTION
**Pull request by pweil-**
Couple issues I'd like to discuss on securing routes.  I'm at the point where I can define a route that has a certificate and have the router pick that up, find a fe/be and write the file to disk.  I am not at the point where it is manipulating the ha-proxy configs:

I think we have a mix of things that are implemented and unimplemented in the router based on the refactoring that was done.

1.   https://github.com/pweil-/origin/blob/router-ssl/plugins/router/template/types.go#L18 It doesn't look like this is used anywhere, is it safe to remove?  If not, was is the intended purpose?  The places where backends are created show this slice being set to null
2.  https://github.com/pweil-/origin/blob/router-ssl/plugins/router/template/types.go#L16-L17 is this supposed to be where the optional path components of the route are stored (www.example.com/path)?  I also think that this is not implemented wholly
3.  The way I've implemented the certificate definition has it on the route's json, not the service or endpoints.  This introduces a race condition that I don't have a good solution for yet.  In summary, a fully constructed router.Frontend is a combination of the pods, service, AND route.  If a secure route is created before the pods and service then it will not be able to find a router.Backend to store the certificates.  Since some of these structures were initially mocked up in the implementation I was wondering if others had alternative approaches in mind
4.  https://github.com/pweil-/origin/blob/router-ssl/plugins/router/template/types.go#L20 I've reused the routeapi constants for termination in the router plugin.  Do you think this is leaky or appropriate (there used to be extra constants in the router plugin itself that I removed in favor of the new ones)?

@rajatchopra @pmorie

### CODE REVIEW

**Comment by pweil-** [comment]
@rchopra  Can you validate that this is the correct approach on the HAProxy side of things?

UC 1: Edge termination with SNI
```
frontend public_ssl
    bind :443
    mode tcp
   ....
    use_backend be_sni if { ssl_fc_has_sni } && <if not in the pass through mappings>
    # pass through mode for everything else
    default_backend be_no_sni

be_sni
   mode tcp
   server fe_sni 127.0.0.1:10444 weight 1 send-proxy

frontend fe_sni
  # explict bind for keys with pass phrases
  bind 127.0.0.1:10444 ssl <explict cert file> <key pass phrase> <if sni check for host name>
  # catch all for non pw protected keys
  bind 127.0.0.1:10444 ssl crt /var/lib/haproxy/conf/certs accept-proxy

  ... send to backends ....
```

**Comment by rchopra** [comment]
I afraid you have the wrong guy. I've never worked on this project.

**Comment by pweil-** [comment]
:smile: Sorry about that @rchopra !!

This was meant for @rajatchopra

**Comment by pweil-** [comment]
@rajatchopra - after playing with it a bit it looks like you can't put the pass phrase inline and cannot use a pass phrase dialog like Apache allows to automate the prompt.  If you know how this was handled in v2 maybe we can use the same technique or contribute something to HAProxy that allows us to specify an executable a la Apache's `SSLPassPhraseDialog` (http://httpd.apache.org/docs/2.2/mod/mod_ssl.html#sslpassphrasedialog)

**Comment by pweil-** [comment]
@rajatchopra @pmorie @abhgupta - I believe this is in a working state for serving custom ssl certs based on sni and passthrough based on sni.  Non-sni enabled requests will go to a generic backend that tries to terminate ssl with a dummy cert.  

If you have some time I'd like to get a code review.  Some of the comments still need cleaned up but I think the guts are correct now.

**Comment by pweil-** [comment]
Found something missing for sni passthrough, need to make a tcp backend specifically for that.  This is the end flow that I'm trying to achieve (since reading a template file isn't going a bit confusing) https://docs.google.com/a/redhat.com/drawings/d/1fRsvKg1iuY1EfQ-C3O6s8lxxouapzuCwVz7jFUKDUsc/edit

**Pull request closed without merging**
