### PR TITLE
namespace aware proxier and lb

### PR DESCRIPTION
**Pull request by pweil-**
This is just to show you what I've done that seems to be working and gather feedback if this is not a feasable solution.  I need to clean it up and put it into an actual k8s request and so some in depth testing but this allows me to have create the services with the same name and curl them both

```
[vagrant@openshiftdev ~]$ osc get -n ns1 services && osc get -n ns2 services
NAME                LABELS                            SELECTOR            IP                  PORT
database            template=ruby-helloworld-sample   name=database       172.30.17.125       5434
NAME                LABELS                            SELECTOR            IP                  PORT
database            template=ruby-helloworld-sample   name=database       172.30.17.200       5434
[vagrant@openshiftdev ~]$ osc get -n ns1 pods && osc get -n ns2 pods
POD                 IP                  CONTAINER(S)               IMAGE(S)            HOST                           LABELS                                                                                          STATUS
database-1-r4y5g    172.17.0.28         ruby-helloworld-database   mysql               openshiftdev.local/127.0.0.1   deployment=database-1,deploymentconfig=database,name=database,template=ruby-helloworld-sample   Running
POD                 IP                  CONTAINER(S)               IMAGE(S)            HOST                           LABELS                                                                                          STATUS
database-1-wgqmy    172.17.0.29         ruby-helloworld-database   mysql               openshiftdev.local/127.0.0.1   deployment=database-1,deploymentconfig=database,name=database,template=ruby-helloworld-sample   Running

[vagrant@openshiftdev ~]$ curl 172.30.17.125:5434
5.6.23y{}%<?gh��TL_x`Uk;%B`<mysql_native_password!��#08S01Got packets out of order

[vagrant@openshiftdev ~]$ curl 172.30.17.200:5434
5.6.23e'0\\=X$��H|[2(mqp\^Dtmysql_native_password!��#08S01Got packets out of order[vagrant@openshiftdev ~]$ 
[vagrant@openshiftdev ~]$ 

[vagrant@openshiftdev ~]$ sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere             anywhere             ADDRTYPE match dst-type LOCAL
KUBE-PORTALS-CONTAINER  all  --  anywhere             anywhere            

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
DOCKER     all  --  anywhere            !loopback/8           ADDRTYPE match dst-type LOCAL
KUBE-PORTALS-HOST  all  --  anywhere             anywhere            

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  172.17.0.0/16        anywhere            

Chain DOCKER (2 references)
target     prot opt source               destination         

Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  anywhere             172.30.17.2          /* default:kubernetes */ tcp dpt:https redir ports 43305
REDIRECT   tcp  --  anywhere             172.30.17.1          /* default:kubernetes-ro */ tcp dpt:http redir ports 40680
REDIRECT   tcp  --  anywhere             172.30.17.125        /* ns1:database */ tcp dpt:sgi-arrayd redir ports 57244
REDIRECT   tcp  --  anywhere             172.30.17.200        /* ns2:database */ tcp dpt:sgi-arrayd redir ports 48135

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             172.30.17.2          /* default:kubernetes */ tcp dpt:https to:10.0.2.15:43305
DNAT       tcp  --  anywhere             172.30.17.1          /* default:kubernetes-ro */ tcp dpt:http to:10.0.2.15:40680
DNAT       tcp  --  anywhere             172.30.17.125        /* ns1:database */ tcp dpt:sgi-arrayd to:10.0.2.15:57244
DNAT       tcp  --  anywhere             172.30.17.200        /* ns2:database */ tcp dpt:sgi-arrayd to:10.0.2.15:48135

```

### CODE REVIEW

**Comment by pweil-** [comment]
@bparees @ironcladlou @ncdc

**Comment by ncdc** [comment]
Cool, but wouldn't updating the proxier to use cache.Reflector make more sense? I think we need to talk to the Google team to find out if there's a reason to keep the proxier using its own caching mechanism, or if we can just convert it to use Reflector, which is namespace aware now.

**Comment by pmorie** [comment]
@ncdc I don't think there's a reason for the upstream proxier to use the custom config stuff -- except that that custom config predates the reflector.  We should def open an upstream issue for this.

@pweil- I assume this is not meant to land, since it includes a patch to Godep'd upstream code.  Confirm/deny?

**Comment by pmorie** [comment]
@pweil- Disregard, I see that this is a PR into your master branch, not origin's master.

**Comment by pweil-** [comment]
@ncdc @pmorie - I'll go ahead and create an issue for this upstream.

**Comment by pweil-** [comment]
closing, upstream issue is https://github.com/GoogleCloudPlatform/kubernetes/issues/4288

**Pull request closed without merging**
